name = "Flatland"
uuid = "bf95c41c-5acb-4adb-a9da-d7e97402d07e"
authors = ["Guillaume Dalle", "Chun-Tso Tsai"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
